const $=s=>document.querySelector(s),K=n=>'n99_'+n,G=(n,d=0)=>{let v=localStorage.getItem(K(n));return v===null?d:+v},S=(n,v)=>localStorage.setItem(K(n),v);
let st={g:null,run:0,ready:0,start:0,raf:0,to:0,pos:1,dir:1,tgt:null,ctx:null,tick:0,share:'',locked:0};
const names={timer:['PERFECT TIMER','Stop at exactly 1.000 seconds. The timer hides after 0.500s — keep counting in your head.'],stop:['PERFECT STOP','Tap START, then stop the moving white marker inside the bright green target.'],reaction:['REACTION TEST','Tap START, wait for the entire box to turn bright green, then tap the green box.']};
const home=$('#home'),game=$('#game'),title=$('#title'),prompt=$('#prompt'),play=$('#play'),res=$('#res'),primary=$('#primary'),best=$('#best'),att=$('#att'),tot=$('#tot'),bst=$('#bst'),modal=$('#modal'),mg=$('#mg'),ms=$('#ms'),mm=$('#mm'),mr=$('#mr'),back=$('#back'),closeBtn=$('#close'),retryBtn=$('#retry'),copyBtn=$('#copy');

const pick=a=>a[Math.floor(Math.random()*a.length)];
const ROAST={
 timer:{
  perfect:['PERFECT. That should not have happened.','Okay, that was disgusting.','You actually hit it. I hate that.'],
  near:['OH THAT’S DISGUSTINGLY CLOSE.','Imagine missing by THAT 💀','Screenshot it. Frame your failure.','You’re gonna think about this in bed.','ONE. TINY. TAP.','Your thumb sold.','99% really means YOU.','You basically won. Basically.','That miss needs a support group.','I’d uninstall after that one.','Your phone felt that hesitation.','You can literally SEE the win from here.'],
  mid:['Bro counted with vibes.','You had ONE second.','Your internal clock needs batteries.','I’ve seen microwaves time better.','Did you sneeze halfway through?','Maybe try counting out loud.','That tap had a layover.','1.00. Not 1.whatever-that-was.','Your stopwatch is embarrassed.','Bro experienced time differently.'],
  bad:['Were your eyes closed?','Calendar might be more your speed.','That wasn’t even the same ZIP code.','Bro invented a new second.','You weren’t even close 💀','NASA has officially stopped calling.','Delete the clock app. You don’t deserve it.','A broken clock just laughed at you.','Your sense of time is purely decorative.','That second lasted three business days.','You counting Mississippi or Massachusetts?','Even your alarm clock is disappointed.','Time itself filed a complaint.','That was less “perfect timer,” more “eventually.”']
 },
 stop:{
  great:['DISGUSTINGLY GOOD.','Okay, aim-bot. Calm down.','That was actually nasty.','Fine. You can aim.'],
  hit:['Inside. Now do it cleaner.','You hit it. Barely counts.','Okay, technically a hit.','Target survived. Your ego won’t.'],
  near:['YOU WERE LITERALLY THERE.','That pixel owns you now.','One molecule away 💀','Your thumb betrayed the bloodline.','How do you even miss by THAT LITTLE?','That hurts more than a normal miss.','99% IMPOSSIBLE sends its regards.','You touched greatness and let go.','Don’t look at the percentage. It’ll hurt.','Your next tap better be personal.','I know you’re pressing TRY AGAIN.','The target is laughing.'],
  bad:['Were you aiming at something else?','The target is the bright part, champ.','Bro stopped in another neighborhood.','Your thumb needs glasses.','GPS couldn’t explain that miss.','That target was HUGE 💀','Aim sold separately.','You saw the target, right?','Stormtrooper accuracy.','That marker wanted nothing to do with the target.','Bro just tapped somewhere.','The target is considering moving.','You couldn’t hit water falling out of a boat.','At least you hit the screen.','Your finger has free will.','The target filed a restraining order.','You aimed using thoughts and prayers.','Precision has left the chat.','That wasn’t a miss. That was a relocation.','The target watched you drive straight past.','Bro saw TARGET and chose adventure.']
 },
 reaction:{
  elite:['OKAY… WHO GAVE YOU ESP?','That thumb is suspicious.','Do that again. I dare you.','Almost superhuman. Almost.','Okay, that was nasty.','I hate that that was actually good.'],
  good:['Your thumb finally woke up.','WAIT. You might actually have this.','Don’t get cocky.','One more and I’ll stop talking.','Fast. Annoyingly fast.'],
  slow:['Did the signal have to reach your brain first?','Bro reacted by mail.','Internet Explorer reflexes.','Your thumb needed manager approval.','A refrigerator reacts faster.','Were you waiting for written permission?','Bro had to process the information.','That reaction came with shipping.','Your neurons are on PTO.','The light turned green yesterday.','Dial-up nervous system.','Did you have to unlock your thumb?','My grandma already tapped.','Your brain sent the signal economy class.','Bro saw GO and scheduled it for later.','Reaction time measured in business days.','The dinosaurs reacted faster. They’re extinct.','Your thumb was buffering.','We almost sent a search party.','I could’ve made dinner while you reacted.','Your nervous system needs a software update.','GO means now, by the way.','Did you stop for snacks?','The button started wondering if you were okay.','Your reflexes have a loading screen.','That wasn’t reaction time. That was a decision.'],
  early:['BRO IT DIDN’T EVEN SAY GO 💀','Congratulations, you reacted to nothing.','Psychic powers: denied.','Patience lasted 0.2 seconds.','Your thumb has trust issues.','You fought a button that wasn’t ready.','Bro tried to predict the future.','False start. Olympic career over.','You got nervous, didn’t you?','The intrusive thought won.','WAIT means WAIT 😭','You just lost to your own finger.']
 }
};

function stats(){tot.textContent=G('total');bst.textContent=G('bestStreak');if(st.g)att.textContent=G(st.g+'_attempts')}
function bump(){S('total',G('total')+1);S(st.g+'_attempts',G(st.g+'_attempts')+1);stats()}
function streak(ok){let c=ok?G('currentStreak')+1:0;S('currentStreak',c);if(c>G('bestStreak'))S('bestStreak',c);stats()}
function pb(){let v=localStorage.getItem(K(st.g+'_best'));if(v===null)return'—';v=+v;return st.g==='reaction'?Math.round(v)+'ms':st.g==='timer'?v.toFixed(3)+'s':v.toFixed(1)+'%'}
function deltaMark(key,current,unit,decimals=0){let raw=localStorage.getItem(K(key));S(key,current);if(raw===null)return'';let prev=+raw,diff=prev-current,eps=unit==='ms'?.5:.0000001;if(Math.abs(diff)<=eps)return'<div style="margin-top:8px;font-size:11px;letter-spacing:.7px;color:#90909c;font-weight:800">HOLD THE LINE</div>';if(diff>0){let n=Math.abs(diff).toFixed(decimals);return'<div style="margin-top:8px;font-size:11px;letter-spacing:.7px;color:#00FFA3;font-weight:800">'+n+unit+' CLOSER ↑</div>'}return'<div style="margin-top:8px;font-size:11px;letter-spacing:.7px;color:#FF5A7D;font-weight:800">YOU HAD IT LAST TIME ↓</div>'}

function audio(){let A=window.AudioContext||window.webkitAudioContext;if(!A)return null;if(!st.ctx)st.ctx=new A;if(st.ctx.state==='suspended')st.ctx.resume();return st.ctx}
function tone(f,d=.06,t='sine',v=.04,w=0){let c=audio();if(!c)return;let o=c.createOscillator(),g=c.createGain(),s=c.currentTime+w;o.type=t;o.frequency.value=f;g.gain.setValueAtTime(.0001,s);g.gain.exponentialRampToValueAtTime(v,s+.006);g.gain.exponentialRampToValueAtTime(.0001,s+d);o.connect(g).connect(c.destination);o.start(s);o.stop(s+d+.02)}
function ticks(mode){untick();let b=mode==='timer'?250:mode==='stop'?190:150,i=0,ms=mode==='reaction'?360:190;st.tick=setInterval(()=>tone(b+Math.min(420,++i*11),.035,mode==='reaction'?'sine':'square',.018),ms)}
function untick(){clearInterval(st.tick);st.tick=0}
function failSound(){untick();tone(150,.12,'sawtooth',.08);tone(85,.18,'square',.05,.05)}
function win(t){untick();let a=t==='perfect'?[392,523,659,784,1047,1319]:t==='epic'?[523,659,784,1047]:t==='strong'?[440,660,880]:[520,660];a.forEach((f,i)=>tone(f,.14,'triangle',t==='perfect'?.09:.06,i*.06));if(t==='perfect')tone(2093,.35,'sine',.08,.38)}
function tier(a){return a>=99.95?'perfect':a>=99.5?'epic':a>=97?'strong':a>=90?'subtle':'fail'}
function rtier(ms){return ms<=170?'perfect':ms<=200?'epic':ms<=230?'strong':ms<=280?'subtle':'fail'}
function fx(t,isPB,fail){play.className='play';document.body.className='';if(fail){play.classList.add('shake');document.body.classList.add('red');failSound();navigator.vibrate?.([25,35,45]);return}play.classList.add(t);document.body.classList.add(t==='perfect'?'gold':isPB||t==='epic'?'greenbg':'');win(t);navigator.vibrate?.(t==='perfect'?[30,40,70,40,110]:30);if(t==='epic'||t==='perfect')conf(t==='perfect'?65:30);if(t==='perfect')fireworks(3);else if(t==='epic')fireworks(1)}
function conf(n){for(let i=0;i<n;i++){let e=document.createElement('i');e.className='conf';e.style.left=Math.random()*100+'%';e.style.setProperty('--x',(Math.random()-.5)*180+'px');e.style.setProperty('--d',(.8+Math.random()*.8)+'s');e.style.setProperty('--h',(45+Math.random()*70));document.body.appendChild(e);setTimeout(()=>e.remove(),1700)}}
const FWC=['#FF2E95','#00E5FF','#8B5CF6','#FFD700','#FFB020','#00FFA3'];
function fireworks(bursts){for(let b=0;b<bursts;b++)setTimeout(()=>{let ox=15+Math.random()*70,oy=12+Math.random()*40,n=22;for(let i=0;i<n;i++){let e=document.createElement('i');e.className='fw';let ang=(i/n)*Math.PI*2+Math.random()*.3,dist=60+Math.random()*100;e.style.setProperty('--ox',ox+'vw');e.style.setProperty('--oy',oy+'vh');e.style.setProperty('--fx',(Math.cos(ang)*dist)+'px');e.style.setProperty('--fy',(Math.sin(ang)*dist)+'px');e.style.setProperty('--fc',FWC[Math.floor(Math.random()*FWC.length)]);e.style.setProperty('--fd',(.6+Math.random()*.4)+'s');document.body.appendChild(e);setTimeout(()=>e.remove(),1150)}},b*170)}

function openGame(g){st.g=g;home.classList.remove('on');game.classList.remove('g-timer','g-stop','g-reaction');game.classList.add('on','g-'+g);title.textContent=names[g][0];prompt.textContent=names[g][1];reset()}
function reset(){cancelAnimationFrame(st.raf);clearTimeout(st.to);untick();st.run=st.ready=0;st.locked=0;st.tgt=null;modal.classList.add('hide');res.classList.add('hide');primary.textContent='START';play.className='play';document.body.className='';if(st.g==='timer')play.innerHTML='<div class="timer"><div class="num">0.000</div><div class="note">VISIBLE UNTIL 0.500s</div></div>';if(st.g==='stop')play.innerHTML='<div class="stopstage"><b class="sl">PRESS START TO BEGIN</b><div class="track"><div class="target"></div><div class="marker"></div></div><div class="note">WHITE LINE → GREEN TARGET</div></div>';if(st.g==='reaction')play.innerHTML='<div class="rx"><b>READY?</b><div>Press START below.</div></div>';best.textContent=pb();stats()}
function show(score,roast,meta,share,t,isPB,fail,delta=''){res.innerHTML='<b>'+score+'</b>'+(isPB?'<div class="new">NEW PERSONAL BEST</div>':'')+'<div>'+roast+'</div>'+delta;res.classList.remove('hide');mg.textContent=names[st.g][0];ms.textContent=score;mm.textContent=meta||'';mm.classList.toggle('hide',!meta);mr.innerHTML=roast+delta;st.share=share;if(copyBtn)copyBtn.textContent='COPY TIKTOK CAPTION';modal.classList.remove('hide');fx(t,isPB,fail);best.textContent=pb()}
function nearReveal(kind,label,sub,cb){st.locked=1;play.classList.add('nearhold');let v=document.createElement('div');v.className='nearveil '+kind;v.innerHTML='<b>'+label+'</b><span>'+sub+'</span>';play.appendChild(v);let c=audio();if(c){let o=c.createOscillator(),g=c.createGain(),n=c.currentTime;o.type='sine';o.frequency.setValueAtTime(135,n);o.frequency.exponentialRampToValueAtTime(230,n+.36);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.055,n+.03);g.gain.exponentialRampToValueAtTime(.0001,n+.39);o.connect(g).connect(c.destination);o.start(n);o.stop(n+.4)}setTimeout(()=>{v.remove();play.classList.remove('nearhold');st.locked=0;cb()},380)}

function timerStart(){audio();st.run=1;st.start=performance.now();primary.textContent='STOP';ticks('timer');let n=play.querySelector('.num'),q=play.querySelector('.note');let loop=()=>{let t=(performance.now()-st.start)/1000;if(t<.5){n.textContent=t.toFixed(3);q.textContent='VISIBLE UNTIL 0.500s'}else{n.textContent='???';n.classList.add('green');q.textContent='TIMER HIDDEN — KEEP COUNTING'}st.raf=requestAnimationFrame(loop)};st.raf=requestAnimationFrame(loop)}
function timerStop(){cancelAnimationFrame(st.raf);untick();st.run=0;let t=(performance.now()-st.start)/1000,d=Math.abs(1-t),a=Math.max(0,100-d*100),raw=localStorage.getItem(K('timer_best')),old=raw===null?null:+raw,isPB=old===null||d<Math.abs(1-old);bump();if(isPB)S('timer_best',t);streak(a>=97);let ro=d<.0005?pick(ROAST.timer.perfect):d<=.01?pick(ROAST.timer.near):d<=.12?pick(ROAST.timer.mid):pick(ROAST.timer.bad),ti=tier(a),delta=deltaMark('timer_lastD',d,'s',3),done=()=>{show(t.toFixed(3)+'s',ro,a.toFixed(1)+'% accuracy',`I hit ${t.toFixed(3)}s (${a.toFixed(1)}%) on Perfect Timer in 99% IMPOSSIBLE 💀 bet you can't get closer to 1.000s.`,ti,isPB,ti==='fail',delta);primary.textContent='TRY AGAIN'};if(a>=98.5&&a<99.5){nearReveal('timer',d.toFixed(3)+'s AWAY','SO CLOSE',done)}else done()}

function stopStart(){audio();st.run=1;primary.textContent='STOP';ticks('stop');let tg=play.querySelector('.target'),m=play.querySelector('.marker'),sl=play.querySelector('.sl'),ss=Math.min(8,G('stop_streak')),w=Math.max(9,22-ss*1.6),x=12+Math.random()*(76-w);tg.style.left=x+'%';tg.style.width=w+'%';sl.textContent='TAP STOP WHEN WHITE HITS GREEN';st.pos=1;st.dir=1;let last=performance.now(),speed=62+ss*8;let loop=now=>{let dt=Math.min((now-last)/1000,.05);last=now;st.pos+=st.dir*speed*dt;if(st.pos>=98)st.pos=98,st.dir=-1;if(st.pos<=1)st.pos=1,st.dir=1;m.style.left=st.pos+'%';st.raf=requestAnimationFrame(loop)};st.tgt={x,w};st.raf=requestAnimationFrame(loop)}
function stopStop(){if(!st.tgt)return;cancelAnimationFrame(st.raf);untick();st.run=0;let c=st.tgt.x+st.tgt.w/2,d=Math.abs(st.pos-c),sc=Math.max(0,100-d/50*100),raw=localStorage.getItem(K('stop_best')),old=raw===null?null:+raw,isPB=old===null||sc>old,hit=st.pos>=st.tgt.x&&st.pos<=st.tgt.x+st.tgt.w,edgeDist=hit?0:Math.min(Math.abs(st.pos-st.tgt.x),Math.abs(st.pos-(st.tgt.x+st.tgt.w)));bump();if(isPB)S('stop_best',sc);S('stop_streak',hit?G('stop_streak')+1:0);streak(sc>=97);let ro=hit?(sc>98?pick(ROAST.stop.great):pick(ROAST.stop.hit)):(edgeDist<=3?pick(ROAST.stop.near):pick(ROAST.stop.bad)),ti=tier(sc),delta=deltaMark('stop_lastD',d,'%',1),done=()=>{show(sc.toFixed(1)+'%',ro,hit?'TARGET HIT':'TARGET MISSED',`I got ${sc.toFixed(1)}% on Perfect Stop in 99% IMPOSSIBLE and my phone almost blew up 💀 bet you can't beat this.`,ti,isPB,!hit||ti==='fail',delta);primary.textContent='TRY AGAIN'};if(!hit&&edgeDist<=3){nearReveal('stop',d.toFixed(1)+'% FROM CENTER','MISSED BY '+edgeDist.toFixed(1)+'% OF TRACK',done)}else done()}

function rxStart(){audio();st.run=1;st.ready=0;primary.textContent='WAIT FOR GREEN…';ticks('reaction');let r=play.querySelector('.rx');r.className='rx wait';r.innerHTML='<b>WAIT…</b><div>Do not tap yet. The whole box will turn GREEN.</div>';st.to=setTimeout(()=>{if(!st.run)return;untick();tone(920,.08,'square',.05);st.ready=1;st.start=performance.now();r.className='rx go';r.innerHTML='<b>GO!</b><div>TAP THIS GREEN BOX NOW</div>';primary.textContent='TAP GREEN BOX!';navigator.vibrate?.(30)},1600+Math.random()*1800)}
function rxHit(){if(!st.run)return;if(!st.ready){clearTimeout(st.to);untick();st.run=0;bump();streak(false);let r=play.querySelector('.rx');r.className='rx early';r.innerHTML='<b>TOO EARLY</b><div>Wait for BRIGHT GREEN.</div>';show('TOO EARLY',pick(ROAST.reaction.early),'NO TIME RECORDED','I got baited by Reaction Test in 99% IMPOSSIBLE and tapped TOO EARLY 💀 bet you do the same.','fail',false,true,'');primary.textContent='TRY AGAIN';return}let msr=performance.now()-st.start;st.run=st.ready=0;bump();let raw=localStorage.getItem(K('reaction_best')),old=raw===null?null:+raw,isPB=old===null||msr<old;if(isPB)S('reaction_best',msr);streak(msr<=230);let ro=msr<180?pick(ROAST.reaction.elite):msr<=250?pick(ROAST.reaction.good):pick(ROAST.reaction.slow),ti=rtier(msr),gap=old===null?null:msr-old,delta=deltaMark('reaction_lastMs',msr,'ms',0),done=()=>{show(Math.round(msr)+'ms',ro,msr<=170?'ELITE REACTION':'REACTION TIME',`I hit ${Math.round(msr)}ms on Reaction Test in 99% IMPOSSIBLE ⚡ bet your reflexes are slower.`,ti,isPB,ti==='fail',delta);primary.textContent='TRY AGAIN'};if(msr>=231&&msr<=250&&old!==null&&!isPB&&gap>0){nearReveal('reaction',Math.round(gap)+'ms FROM YOUR BEST','SO CLOSE',done)}else done()}

primary.onpointerup=e=>{e.preventDefault();if(st.locked)return;audio();if(primary.textContent==='TRY AGAIN')return reset();if(st.g==='timer')st.run?timerStop():timerStart();else if(st.g==='stop')st.run?stopStop():stopStart();else if(st.g==='reaction'&&!st.run)rxStart()};
play.onpointerup=e=>{if(st.locked)return;if(st.g==='reaction'&&st.run){e.preventDefault();rxHit()}};
document.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>openGame(b.dataset.g));
back.onclick=()=>{reset();game.classList.remove('on');home.classList.add('on');st.g=null;stats()};
closeBtn.onclick=()=>modal.classList.add('hide');
retryBtn.onclick=reset;
modal.onclick=e=>{if(e.target===modal)modal.classList.add('hide')};
if(copyBtn)copyBtn.onclick=async()=>{let ok=0;try{await navigator.clipboard.writeText(st.share);ok=1}catch(e){let t=document.createElement('textarea');t.value=st.share;document.body.appendChild(t);t.select();try{ok=document.execCommand('copy')}catch{}t.remove()}copyBtn.textContent=ok?'COPIED ✓':'COPY FAILED — PRESS & HOLD';if(ok){tone(740,.07);tone(980,.08,'sine',.04,.06);navigator.vibrate?.(20)}};
stats();