/* 99% IMPOSSIBLE — Cosmetics + Store layer (standalone, additive) */
(()=>{
const CK=n=>'n99_cos_'+n;
const THEMES={
 default:{name:'DEFAULT',free:true,targetName:'GREEN',vars:{'--neon-green':'#00FFA3','--neon-green-dark':'#00B372'}},
 cyberpunk:{name:'CYBERPUNK',price:'$3.99 · RAGE PASS',targetName:'PINK',vars:{'--neon-green':'#FF00FF','--neon-green-dark':'#A800A8','--neon-pink':'#F0F','--neon-cyan':'#00FFF9','--neon-purple':'#7B2FFF','--neon-orange':'#FF9900','--neon-red':'#FF003C','--accent-gold':'#FFEE00'}},
 goldonly:{name:'GOLD ONLY',price:'$3.99 · RAGE PASS',targetName:'GOLD',vars:{'--neon-green':'#FFD700','--neon-green-dark':'#B8860B','--neon-pink':'#FFD700','--neon-cyan':'#F4C430','--neon-purple':'#D4AF37','--neon-orange':'#FFC300','--neon-red':'#B8860B','--accent-gold':'#FFF3B0'}},
 synthwave:{name:'SYNTHWAVE',price:'$3.99 · RAGE PASS',targetName:'CYAN',vars:{'--neon-green':'#08D9D6','--neon-green-dark':'#087F7D','--neon-pink':'#FF2E63','--neon-cyan':'#08D9D6','--neon-purple':'#6A2C70','--neon-orange':'#F08A5D','--neon-red':'#EA355A','--accent-gold':'#FFD460'}}
};
function hasPass(){return localStorage.getItem(CK('ragepass'))==='1'}
function isUnlocked(id){return THEMES[id].free||hasPass()||localStorage.getItem(CK('theme_'+id))==='1'}
function activeId(){const id=localStorage.getItem(CK('active'))||'default';return THEMES[id]?id:'default'}
function syncColorWords(){const t=THEMES[activeId()]||THEMES.default,name=t.targetName,low=name.toLowerCase();const title=document.querySelector('#title')?.textContent||'',prompt=document.querySelector('#prompt');if(title==='PERFECT STOP'&&prompt)prompt.textContent='Tap START, then stop the moving white marker inside the bright '+low+' target.';if(title==='REACTION TEST'&&prompt)prompt.textContent='Tap START, wait for the entire box to turn bright '+low+', then tap the '+low+' box.';const note=document.querySelector('.stopstage .note');if(note)note.textContent='WHITE LINE → '+name+' TARGET';const homeReaction=document.querySelector('.card[data-g="reaction"] small');if(homeReaction)homeReaction.textContent='Tap the instant it turns '+low}
function applyTheme(id){const t=THEMES[id];if(!t||!isUnlocked(id))id='default';const t2=THEMES[id];const root=document.documentElement.style;const keys=new Set();Object.values(THEMES).forEach(th=>Object.keys(th.vars||{}).forEach(k=>keys.add(k)));keys.forEach(k=>root.removeProperty(k));Object.entries(t2.vars||{}).forEach(([k,v])=>root.setProperty(k,v));localStorage.setItem(CK('active'),id);syncColorWords();requestAnimationFrame(syncColorWords)}
const style=document.createElement('style');style.textContent=`
.cos-fab{position:fixed;right:14px;top:76px;bottom:auto;width:42px;height:42px;border-radius:50%;background:linear-gradient(180deg,var(--neon-pink,#FF2E95) 0%,#C4116A 100%);border:2px solid rgba(255,255,255,.2);color:#fff;font-size:18px;box-shadow:0 4px 14px rgba(0,0,0,.4);z-index:40;touch-action:manipulation}
.petty-voice{position:fixed!important;left:auto!important;right:66px!important;top:76px!important;bottom:auto!important;width:42px!important;height:42px!important;font-size:17px!important}
body:has(#modal:not(.hide)) .cos-fab{opacity:.28;pointer-events:none}
.cos-modal{position:fixed;inset:0;background:#000d;backdrop-filter:blur(6px);z-index:41;display:none;align-items:center;justify-content:center;padding:20px}.cos-modal.on{display:flex}.cos-box{width:min(100%,440px);max-height:82vh;overflow-y:auto;background:linear-gradient(180deg,#13141B 0%,#0D0E12 100%);border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:20px;color:#fff;font-family:'Chakra Petch',system-ui,sans-serif}.cos-box h3{font-family:'Teko','Arial Black',sans-serif;font-size:28px;letter-spacing:1px;margin:0 0 4px}.cos-box .sub{color:#9c9ca8;font-size:12px;margin-bottom:16px}.cos-close{position:absolute;top:14px;right:18px;background:none;border:none;color:#fff;font-size:22px}.cos-card{border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:12px;margin-bottom:10px;display:flex;justify-content:space-between;align-items:center;gap:10px}.cos-swatch{display:flex;gap:4px;margin-top:6px}.cos-swatch i{width:14px;height:14px;border-radius:4px;display:block}.cos-btn{border:none;border-radius:8px;padding:9px 14px;font-family:'Teko','Arial Black',sans-serif;font-size:1rem;letter-spacing:.5px;text-transform:uppercase;touch-action:manipulation}.cos-btn.use{background:#2A2A36;color:#fff}.cos-btn.buy{background:linear-gradient(180deg,var(--neon-orange,#FFB020) 0%,#B87700 100%);color:#231400}.cos-btn.active{background:linear-gradient(180deg,var(--neon-green,#00FFA3) 0%,var(--neon-green-dark,#00B372) 100%);color:#031}.cos-note{font-size:11px;color:#9c9ca8;margin-top:14px;line-height:1.5;border-top:1px solid rgba(255,255,255,.08);padding-top:12px}`;document.head.appendChild(style);
const fab=document.createElement('button');fab.className='cos-fab';fab.textContent='🎨';fab.setAttribute('aria-label','Store');document.body.appendChild(fab);
const modal=document.createElement('div');modal.className='cos-modal';modal.innerHTML=`<div class="cos-box" style="position:relative"><button class="cos-close">×</button><h3>STORE</h3><div class="sub">Cosmetics only. Never pay-to-win.</div><div id="cosThemeList"></div><div class="cos-note" id="cosNote"></div></div>`;document.body.appendChild(modal);
function renderList(){const list=modal.querySelector('#cosThemeList');list.innerHTML='';Object.entries(THEMES).forEach(([id,t])=>{const unlocked=isUnlocked(id);const active=activeId()===id;const card=document.createElement('div');card.className='cos-card';const swatches=t.vars?Object.values(t.vars).filter(v=>/^#/.test(v)).slice(0,4).map(c=>`<i style="background:${c}"></i>`).join(''):'';card.innerHTML=`<div><div style="font-weight:800;letter-spacing:.5px">${t.name}</div><div class="cos-swatch">${swatches}</div></div>`;const btn=document.createElement('button');if(active){btn.className='cos-btn active';btn.textContent='ACTIVE'}else if(unlocked){btn.className='cos-btn use';btn.textContent='USE';btn.onclick=()=>{applyTheme(id);renderList()}}else{btn.className='cos-btn buy';btn.textContent=t.price||'LOCKED';btn.onclick=()=>tryUnlock(id)}card.appendChild(btn);list.appendChild(card)});modal.querySelector('#cosNote').textContent=hasPass()?'RAGE PASS active (test mode) — all themes unlocked.':'Real payments are not connected yet. Tap a locked theme to preview it.'}
function tryUnlock(id){const ok=confirm(THEMES[id].name+' — '+(THEMES[id].price||'')+'\n\nReal payment is not connected yet. Unlock this for FREE in test mode?');if(ok){localStorage.setItem(CK('ragepass'),'1');applyTheme(id);renderList()}}
fab.onclick=()=>{modal.classList.add('on');renderList()};modal.querySelector('.cos-close').onclick=()=>modal.classList.remove('on');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('on')};
const game=document.querySelector('#game');if(game)new MutationObserver(()=>requestAnimationFrame(syncColorWords)).observe(game,{attributes:true,childList:true,subtree:true,characterData:true});
applyTheme(activeId());
})();