/* 99% IMPOSSIBLE — Cosmetics store with verified Stripe entitlements. */
(()=>{
const CK=n=>'n99_cos_'+n;
const THEMES={
 default:{name:'DEFAULT',free:true,targetName:'GREEN',vars:{'--game-target':'#00FFA3','--neon-green':'#00FFA3','--neon-green-dark':'#00B372','--neon-pink':'#FF2E95','--neon-cyan':'#00D8F6','--neon-purple':'#8B5CF6','--neon-orange':'#FFB020','--neon-red':'#FF2A5F','--accent-gold':'#FFD700'}},
 cyberpunk:{name:'CYBERPUNK',price:'$1.99',targetName:'PINK',vars:{'--game-target':'#FF00FF','--neon-green':'#FF00FF','--neon-green-dark':'#A800A8','--neon-pink':'#F0F','--neon-cyan':'#00FFF9','--neon-purple':'#7B2FFF','--neon-orange':'#FF9900','--neon-red':'#FF003C','--accent-gold':'#FFEE00'}},
 goldonly:{name:'GOLD ONLY',price:'$1.99',targetName:'GOLD',vars:{'--game-target':'#FFD700','--neon-green':'#FFD700','--neon-green-dark':'#B8860B','--neon-pink':'#FFD700','--neon-cyan':'#F4C430','--neon-purple':'#D4AF37','--neon-orange':'#FFC300','--neon-red':'#B8860B','--accent-gold':'#FFF3B0'}},
 synthwave:{name:'SYNTHWAVE',price:'$1.99',targetName:'CYAN',vars:{'--game-target':'#08D9D6','--neon-green':'#08D9D6','--neon-green-dark':'#087F7D','--neon-pink':'#FF2E63','--neon-cyan':'#08D9D6','--neon-purple':'#6A2C70','--neon-orange':'#F08A5D','--neon-red':'#EA355A','--accent-gold':'#FFD460'}}
};
const initialActive=localStorage.getItem(CK('active'))||'default';
function ent(){return window.N99Entitlements}
function hasPass(){return !!ent()?.isOwned?.('ragepass')}
function isUnlocked(id){return !!THEMES[id]?.free||hasPass()||!!ent()?.isOwned?.(id)}
function activeId(){const id=localStorage.getItem(CK('active'))||'default';return THEMES[id]?id:'default'}
function setText(el,text){if(el&&el.textContent!==text)el.textContent=text}
function syncColorWords(){const t=THEMES[activeId()]||THEMES.default,name=t.targetName,low=name.toLowerCase(),title=document.querySelector('#title')?.textContent||'';if(title==='PERFECT STOP'){setText(document.querySelector('#prompt'),'Tap START, then stop the moving white marker inside the bright '+low+' target.');setText(document.querySelector('.stopstage .note'),'WHITE LINE → '+name+' TARGET');const sl=document.querySelector('.stopstage .sl');if(sl&&/WHITE HITS/i.test(sl.textContent))setText(sl,'TAP STOP WHEN WHITE HITS '+name)}if(title==='REACTION TEST'){setText(document.querySelector('#prompt'),'Tap START, wait for the entire box to turn bright '+low+', then tap the '+low+' box.');const rx=document.querySelector('.rx div');if(rx&&/green|pink|gold|cyan/i.test(rx.textContent))setText(rx,rx.textContent.replace(/green|pink|gold|cyan/gi,low));const p=document.querySelector('#primary');if(p&&/GREEN|PINK|GOLD|CYAN/i.test(p.textContent))setText(p,p.textContent.replace(/GREEN|PINK|GOLD|CYAN/gi,name))}setText(document.querySelector('.card[data-g="reaction"] small'),'Tap the instant it turns '+low)}
function syncPaletteButton(){const t=THEMES[activeId()]||THEMES.default;const name=document.querySelector('.cos-fab .utility-value');if(name)name.textContent=t.name}
function applyVars(id){const t=THEMES[id]||THEMES.default,root=document.documentElement.style,keys=new Set();Object.values(THEMES).forEach(th=>Object.keys(th.vars||{}).forEach(k=>keys.add(k)));keys.forEach(k=>root.removeProperty(k));Object.entries(t.vars||{}).forEach(([k,v])=>root.setProperty(k,v));syncColorWords();syncPaletteButton();setTimeout(syncColorWords,40)}
function applyTheme(id){if(!THEMES[id]||!isUnlocked(id))id='default';localStorage.setItem(CK('active'),id);applyVars(id)}
const style=document.createElement('style');style.textContent=`
:root{--game-target:#00FFA3}.stopstage .target{background:var(--game-target)!important;border-color:rgba(255,255,255,.28)!important}.stopstage .target:before{color:var(--game-target)!important}.rx.go{background:var(--game-target)!important}
.n99-utility-dock{position:fixed;left:50%;bottom:max(10px,env(safe-area-inset-bottom));transform:translateX(-50%);width:min(492px,calc(100vw - 28px));display:grid;grid-template-columns:1fr 1fr;gap:9px;z-index:40;pointer-events:none}.n99-utility-dock>*{pointer-events:auto}.cos-fab,.petty-voice-simple{position:relative!important;inset:auto!important;width:100%!important;height:50px!important;border-radius:12px!important;border:1px solid rgba(255,255,255,.12)!important;background:linear-gradient(180deg,#171922f7,#0d0e12f7)!important;color:#fff!important;box-shadow:0 5px 18px #0009!important;font-family:'Chakra Petch',system-ui!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:9px!important;padding:6px 10px!important;font-size:16px!important;touch-action:manipulation}.utility-icon{font-size:19px}.utility-copy{display:flex;flex-direction:column;align-items:flex-start;line-height:1.05}.utility-label{font-size:9px;font-weight:900;letter-spacing:1.2px;color:#9c9ca8}.utility-value{font-size:11px;font-weight:900;letter-spacing:.55px;color:#fff;margin-top:3px}.petty-voice-simple .utility-state{color:var(--neon-green);text-shadow:0 0 10px color-mix(in srgb,var(--neon-green) 60%,transparent)}.petty-voice-simple.off .utility-state{color:var(--neon-red);text-shadow:0 0 10px color-mix(in srgb,var(--neon-red) 60%,transparent)}body:has(#game.on) .n99-utility-dock{position:absolute;top:calc(100dvh + 8px);bottom:auto;padding-bottom:max(12px,env(safe-area-inset-bottom))}body:has(#game.on){padding-bottom:78px}body:has(#modal:not(.hide)) .n99-utility-dock{opacity:.24;pointer-events:none}.cos-fab:active,.petty-voice-simple:active{transform:translateY(1px);filter:brightness(1.15)}
.cos-modal{position:fixed;inset:0;background:#000d;backdrop-filter:blur(6px);z-index:141;display:none;align-items:center;justify-content:center;padding:20px}.cos-modal.on{display:flex}.cos-box{width:min(100%,440px);max-height:82vh;overflow-y:auto;background:linear-gradient(180deg,#13141B 0%,#0D0E12 100%);border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:20px;color:#fff;font-family:'Chakra Petch',system-ui,sans-serif}.cos-box h3{font-family:'Teko','Arial Black',sans-serif;font-size:28px;letter-spacing:1px;margin:0 0 4px}.cos-box .sub{color:#9c9ca8;font-size:12px;margin-bottom:16px}.cos-close{position:absolute;top:14px;right:18px;background:none;border:none;color:#fff;font-size:22px}.cos-card{border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:12px;margin-bottom:10px;display:flex;justify-content:space-between;align-items:center;gap:10px}.cos-card.bundle{border-color:rgba(255,176,32,.42);background:rgba(255,176,32,.06)}.cos-swatch{display:flex;gap:4px;margin-top:6px}.cos-swatch i{width:14px;height:14px;border-radius:4px;display:block}.cos-btn{border:none;border-radius:8px;padding:9px 14px;font-family:'Teko','Arial Black',sans-serif;font-size:1rem;letter-spacing:.5px;text-transform:uppercase;touch-action:manipulation}.cos-btn.use{background:#2A2A36;color:#fff}.cos-btn.buy{background:linear-gradient(180deg,var(--neon-orange,#FFB020) 0%,#B87700 100%);color:#231400}.cos-btn.active{background:linear-gradient(180deg,var(--neon-green,#00FFA3) 0%,var(--neon-green-dark,#00B372) 100%);color:#031}.cos-note{font-size:11px;color:#9c9ca8;margin-top:14px;line-height:1.5;border-top:1px solid rgba(255,255,255,.08);padding-top:12px}@media(max-width:370px){.n99-utility-dock{gap:6px}.cos-fab,.petty-voice-simple{padding:5px 7px!important}.utility-label{font-size:8px}.utility-value{font-size:10px}}`;document.head.appendChild(style);
const fab=document.createElement('button');fab.className='cos-fab';fab.innerHTML='<span class="utility-icon">🎨</span><span class="utility-copy"><span class="utility-label">CHANGE COLORS</span><span class="utility-value">DEFAULT</span></span>';fab.setAttribute('aria-label','Change color palette');
function installDock(){let dock=document.querySelector('.n99-utility-dock');if(!dock){dock=document.createElement('div');dock.className='n99-utility-dock';document.body.appendChild(dock)}const sound=document.querySelector('.petty-voice-simple');if(sound&&!dock.contains(sound))dock.appendChild(sound);if(!dock.contains(fab))dock.appendChild(fab)}
document.body.appendChild(fab);installDock();setTimeout(installDock,0);setTimeout(installDock,250);
const modal=document.createElement('div');modal.className='cos-modal';modal.innerHTML=`<div class="cos-box" style="position:relative"><button class="cos-close">×</button><h3>STORE</h3><div class="sub">Cosmetics only. Never pay-to-win.</div><div id="cosThemeList"></div><div class="cos-note" id="cosNote"></div></div>`;document.body.appendChild(modal);
async function buy(item){if(!ent()?.purchase){alert('Checkout is still loading. Please try again.');return}await ent().purchase(item)}
function renderList(){const list=modal.querySelector('#cosThemeList');list.innerHTML='';const bundle=document.createElement('div');bundle.className='cos-card bundle';bundle.innerHTML=`<div><div style="font-weight:900;letter-spacing:.5px">RAGE PASS</div><div style="font-size:11px;color:#aaa;margin-top:3px">ALL 3 PREMIUM PALETTES</div></div>`;const bundleBtn=document.createElement('button');bundleBtn.className=hasPass()?'cos-btn use':'cos-btn buy';bundleBtn.textContent=hasPass()?'OWNED':'$3.99';if(!hasPass())bundleBtn.onclick=()=>buy('ragepass');bundle.appendChild(bundleBtn);list.appendChild(bundle);
Object.entries(THEMES).forEach(([id,t])=>{const unlocked=isUnlocked(id),active=activeId()===id,card=document.createElement('div');card.className='cos-card';const swatches=Object.values(t.vars||{}).filter(v=>/^#/.test(v)).slice(0,4).map(c=>`<i style="background:${c}"></i>`).join('');card.innerHTML=`<div><div style="font-weight:800;letter-spacing:.5px">${t.name}</div><div class="cos-swatch">${swatches}</div></div>`;const btn=document.createElement('button');if(active){btn.className='cos-btn active';btn.textContent='ACTIVE'}else if(unlocked){btn.className='cos-btn use';btn.textContent=id==='default'?'USE':'OWNED · USE';btn.onclick=()=>{applyTheme(id);renderList()}}else{btn.className='cos-btn buy';btn.textContent=t.price||'LOCKED';btn.onclick=()=>buy(id)}card.appendChild(btn);list.appendChild(card)});modal.querySelector('#cosNote').textContent=hasPass()?'RAGE PASS OWNED — all premium palettes unlocked.':'Buy one palette for $1.99, or unlock all three with Rage Pass for $3.99.'}
fab.onclick=()=>{modal.classList.add('on');renderList()};modal.querySelector('.cos-close').onclick=()=>modal.classList.remove('on');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('on')};
window.addEventListener('n99:entitlements',()=>{const desired=initialActive;if(desired!=='default'&&isUnlocked(desired))applyTheme(desired);else if(!isUnlocked(activeId()))applyTheme('default');if(modal.classList.contains('on'))renderList()});
document.addEventListener('click',e=>{if(e.target?.closest?.('.card,#primary,#retry,#back,.cos-btn')){setTimeout(syncColorWords,20);setTimeout(syncColorWords,350);setTimeout(syncColorWords,1900)}},false);
window.N99Cosmetics={applyTheme,activeId,syncColorWords,THEMES};
if(initialActive==='default')applyTheme('default');else applyVars('default');
})();