/* 99% IMPOSSIBLE — Petty v6.9: selected-cast first-gesture welcome, Safari-safe for Daisy/Mick */
(()=>{const pp=window.PettyPersonality;if(!pp||pp.__v6)return;pp.__v6=true;const pick=a=>a[Math.floor(Math.random()*a.length)],d=new Date(),h=d.getHours(),day=d.getDay(),m=d.getMonth()+1,n=d.getDate();let p=[];
const holiday=(m===1&&n===1)?['New year. Same thumbs.','New year, new you? Prove it.']:(m===2&&n===14)?['Happy Valentine’s Day. The target still doesn’t love you.','Valentine’s Day and you’re here with me? Awkward.']:(m===3&&n===17)?['Happy St. Patrick’s Day. You’re gonna need the luck.']:(m===7&&n===4)?['Happy Fourth! Your thumbs still need freedom.']:(m===10&&n===31)?['Happy Halloween. That last score was scary.','Halloween? Perfect. Your timing already scares me.']:(m===12&&n===25)?['Merry Christmas! I got you another loss.','Merry Christmas. Santa can’t fix those reflexes.']:(m===12&&n===31)?['New Year’s Eve. One last bad score?']:null;if(holiday)p.push(...holiday);
if(h<5)p.push('Bro. Go to bed.','Fam, why are you awake?','It is WAY too late for this.');else if(h<11)p.push('Morning! Ready to get cooked?','Good morning. Let’s ruin it.','You woke up and chose this?');else if(h<14)p.push('Lunch break? Let’s waste it together.','Eating lunch? Hope your thumbs ate too.');else if(h<18)p.push('Afternoon! You ready to lose?','Back already? Let’s see those thumbs.');else if(h<22)p.push('Evening! Time to get humbled.','Night’s young. Your streak won’t be.');else p.push('Late night? Bad choices already.','Bro. Sleep was an option.');
if(day===1)p.push('Monday AND this game? Rough.');if(day===5)p.push('Friday night and you picked me? Wild.');if(day===0||day===6)p.push('Weekend plans: getting cooked by me?','It’s the weekend. Go outside after this.');
p.push('Oh look who’s back.','Bro came back for more.','You again?! I love the confidence.','Fam, you really missed me?','Round two? Or twenty?','Welcome back, loser. Kidding. Mostly.','Oh good. My favorite victim.','You ready to get cooked?','Back again? Lock in this time.','Mate, we JUST did this.','My guy came back voluntarily.','Alright. Show me something.','Here we go again.','You ready? I’m not going easy.','Bro said “one more try.” Sure.');
const selected=()=>window.N99Character?.get?.()||'petty';
function welcomeText(){const c=selected();if(c==='daisy'||c==='mick'){const a=window.N99CastLines?.[c]?.intro||[];if(a.length)return pick(a).text}return pick(p)}
let g=welcomeText(),ready=false,wantsWelcome=false,said=false,welcomeNotBefore=0,welcomeTimer=0,reactionGateUsed=false;
function sayWelcome(){if(said||window.__N99_CAST_WELCOME_SAID||window.__PETTY_AD_BANTER_LOCK)return;said=true;const c=selected();if(c==='daisy'||c==='mick'){pp.speak?.(g,true,'welcome')}else{pp.speakWelcome?pp.speakWelcome(g,true,'welcome'):pp.speak(g,true,'welcome')}}
function queueWelcome(){if(!ready||!wantsWelcome||said)return;clearTimeout(welcomeTimer);const now=(typeof performance!=='undefined'&&performance.now)?performance.now():Date.now(),wait=Math.max(0,welcomeNotBefore-now);if(wait>0)welcomeTimer=setTimeout(sayWelcome,Math.ceil(wait));else sayWelcome()}
if(selected()==='petty'){try{Promise.resolve(window.preloadPettyVoice?.(g)).then(ok=>{ready=!!ok;queueWelcome()}).catch(()=>{})}catch{}}else ready=true;
function firstGesture(e){if(said||window.__N99_CAST_WELCOME_SAID||e?.target?.classList?.contains('petty-voice')||e?.target?.closest?.('.cast-picker')||window.__PETTY_AD_BANTER_LOCK)return;const c=selected();wantsWelcome=true;g=welcomeText();const now=(typeof performance!=='undefined'&&performance.now)?performance.now():Date.now();if(c==='daisy'||c==='mick'){ready=true;welcomeNotBefore=now;queueWelcome();return}window.unlockPettyAudio?.();welcomeNotBefore=Math.max(welcomeNotBefore,now+100);queueWelcome()}
function gateReactionFirstClick(e){const card=e?.target?.closest?.('[data-g="reaction"]');if(!card||reactionGateUsed||window.__PETTY_WELCOME_STARTED||window.__N99_CAST_WELCOME_SAID||window.__PETTY_AD_BANTER_LOCK)return;reactionGateUsed=true;e.preventDefault?.();e.stopImmediatePropagation?.();let opened=false,timer=0;const open=()=>{if(opened)return;opened=true;clearTimeout(timer);removeEventListener('n99:petty-welcome-start',open);if(typeof window.openGame==='function')window.openGame('reaction');else card.onclick?.()};addEventListener('n99:petty-welcome-start',open,{once:true});timer=setTimeout(open,5000)}
addEventListener('pointerdown',firstGesture,{capture:true});addEventListener('touchstart',firstGesture,{capture:true,passive:true});addEventListener('click',gateReactionFirstClick,{capture:true});pp.version='6.9'})();
