/* 99% IMPOSSIBLE — Petty core v2.9: praise tiers, anti-repeat, ad priority, interruption personality */
(()=>{
const P=n=>'n99_petty_'+n,get=(n,d=null)=>{const v=localStorage.getItem(P(n));return v===null?d:v},set=(n,v)=>localStorage.setItem(P(n),String(v)),q=s=>document.querySelector(s);let lastResultKey='',recent=[],speechActive=false,speechKind='normal',cutoffs=0,nextComplaintAt=6;
const style=document.createElement('style');style.textContent=`.petty-aside{margin:11px auto 2px;padding:8px 10px;max-width:340px;border:1px dashed rgba(255,255,255,.12);border-radius:8px;color:#b8b4c0;font-size:11px;font-weight:800;line-height:1.35}.petty-aside::before{content:'PETTY: ';color:var(--neon-pink,#FF2E95);letter-spacing:.7px}.petty-voice{position:fixed;z-index:40;width:46px;height:46px;border-radius:50%;border:2px solid rgba(255,255,255,.18);background:linear-gradient(180deg,#25202c,#121016);box-shadow:0 4px 14px rgba(0,0,0,.45);color:#fff;font-size:18px;touch-action:manipulation}.petty-voice.off{opacity:.55;filter:grayscale(.65)}body:has(#modal:not(.hide)) .petty-voice{opacity:.28;pointer-events:none}.petty-pop{position:fixed;left:50%;bottom:calc(max(84px,env(safe-area-inset-bottom) + 76px));transform:translateX(-50%);max-width:min(86vw,360px);padding:10px 14px;border-radius:10px;background:#11131bee;border:1px solid rgba(255,255,255,.13);color:#fff;font:800 12px/1.35 'Chakra Petch',system-ui,sans-serif;text-align:center;z-index:55;box-shadow:0 8px 28px #0008;pointer-events:none;animation:pettyPop .18s ease-out}@keyframes pettyPop{from{opacity:0;transform:translate(-50%,8px)}to{opacity:1;transform:translate(-50%,0)}}`;document.head.appendChild(style);
const voiceBtn=document.createElement('button');voiceBtn.className='petty-voice';voiceBtn.setAttribute('aria-label','Toggle Petty voice');document.body.appendChild(voiceBtn);
function voiceOn(){return get('voice','1')==='1'}function sync(){voiceBtn.textContent=voiceOn()?'🔊':'🔇';voiceBtn.classList.toggle('off',!voiceOn())}function chooseVoice(){const vs=speechSynthesis?.getVoices?.()||[];return vs.find(v=>/^en-GB/i.test(v.lang))||vs.find(v=>/^en-/i.test(v.lang))||null}
function speak(text,force=false,kind='normal'){if(window.__PETTY_AD_BANTER_LOCK&&!force)return false;if((!voiceOn()&&!force)||!text)return false;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),v=chooseVoice();if(v)u.voice=v;u.lang=v?.lang||'en-GB';u.rate=.99;u.pitch=.86;u.volume=1;speechKind=kind;speechActive=true;u.onstart=()=>{speechActive=true;speechKind=kind};u.onend=u.onerror=()=>{speechActive=false;speechKind='normal'};speechSynthesis.speak(u);return true}catch{speechActive=false;return false}}
function interruptAndSpeak(t,kind='normal'){if(window.__PETTY_AD_BANTER_LOCK)return false;try{speechSynthesis.cancel()}catch{}speechActive=false;return speak(t,false,kind)}
voiceBtn.onclick=()=>{set('voice',voiceOn()?'0':'1');if(!voiceOn())try{speechSynthesis.cancel()}catch{}speechActive=false;sync()};sync();
const L=(id,text)=>({id,text}),p=(a)=>{let options=a.filter(x=>!recent.includes(x.id));if(!options.length)options=a;const x=options[Math.floor(Math.random()*options.length)];recent.push(x.id);if(recent.length>18)recent.shift();return x};
const pools={
timer:[L('t1','Bro. Can you count?'),L('t2','One second. ONE.'),L('t3','Fam, what was that?'),L('t4','Not even close, mate.'),L('t5','The timer just cooked you.'),L('t6','You guessed, didn’t you?'),L('t7','That was rough, bro.'),L('t8','My grandma counts better.'),L('t9','Bro got beef with one second.'),L('t10','You had one job.'),L('t11','Mate. Slower.'),L('t12','Mate. Faster.'),L('t13','That was your guess?'),L('t14','The clock said nope.'),L('t15','Yeah... run that back.'),L('t16','Bro, lock in.'),L('t17','That second dodged you.'),L('t18','You missed by vibes.'),L('t19','Fam, count with confidence.'),L('t20','The timer is bullying you now.')],
stop:[L('s1','Bro. The box was RIGHT there.'),L('s2','Did you close your eyes?'),L('s3','Fam, aim at the box.'),L('s4','You missed THAT?'),L('s5','The target is literally sitting still.'),L('s6','Mate. It does not move.'),L('s7','Where were you aiming?'),L('s8','Bro aimed at another game.'),L('s9','That was nasty. Not the good kind.'),L('s10','The box is laughing at you.'),L('s11','Almost! Just kidding.'),L('s12','Nah, you’re trolling me.'),L('s13','Your thumb said nope.'),L('s14','Fam. Open your eyes.'),L('s15','HOW did you miss that?'),L('s16','Bro missed the whole neighborhood.'),L('s17','That aim needs help.'),L('s18','My guy went sightseeing.'),L('s19','The box was not hiding.'),L('s20','Mate, that was wild.')],
reaction:[L('r1','Bro fell asleep.'),L('r2','Hello? Anybody home?'),L('r3','Green means GO, mate.'),L('r4','Were you texting?'),L('r5','My grandma tapped first.'),L('r6','Bro needed a warm-up.'),L('r7','That thumb is on vacation.'),L('r8','Wake up, fam.'),L('r9','The green light got bored.'),L('r10','Mate, we are waiting.'),L('r11','You good over there?'),L('r12','Bro lagged in real life.'),L('r13','Your thumb said five more minutes.'),L('r14','That was SLOW slow.'),L('r15','I almost took a nap.'),L('r16','Fam, the light had a birthday.'),L('r17','Bro reacted next week.'),L('r18','That tap came by mail.'),L('r19','My guy buffered.'),L('r20','You saw green eventually, yeah?')],
early:[L('e1','BRO. IT WASN’T EVEN READY.'),L('e2','What are you tapping?!'),L('e3','Fam, wait for the color!'),L('e4','Bro fought an invisible signal.'),L('e5','You panicked. I saw it.'),L('e6','Mate, calm DOWN.'),L('e7','You just tapped air.'),L('e8','Bro said close enough.'),L('e9','The signal left the chat.'),L('e10','Too early, speedy.'),L('e11','Fam, patience exists.'),L('e12','Bro jumped the whole game.'),L('e13','My guy tried to predict the future.'),L('e14','Nahhh, you pressed on a feeling.'),L('e15','Bro, WAIT means wait.'),L('e16','You saw nothing and still committed.')],
slow:[L('sl1','Bro, wake UP.'),L('sl2','Were you making a sandwich?'),L('sl3','Fam, it’s been ready.'),L('sl4','You can tap now, mate.'),L('sl5','That took forever.'),L('sl6','My guy went AFK.'),L('sl7','Bro needed directions.'),L('sl8','You missed the whole moment.'),L('sl9','Mate. Faster than THAT.'),L('sl10','The signal gave up on you.'),L('sl11','Bro, even I got bored.'),L('sl12','Fam, that reaction was ancient.')],
good:[L('g01','Okayyy, that was clean.'),L('g02','Not bad, fam.'),L('g03','Bro actually locked in.'),L('g04','Okay, I see you.'),L('g05','That was kinda nice.'),L('g06','Mate, that was solid.'),L('g07','Low-key clean.'),L('g08','Alright, you got something.'),L('g09','Okay bro, respect.'),L('g10','That was way better.'),L('g11','You’re cooking a little.'),L('g12','Fine. That was good.')],
veryClose:[L('vc1','OOOH! That was close.'),L('vc2','Nahhh, you almost had it!'),L('vc3','Bro! That was RIGHT there.'),L('vc4','Okay, that one hurt.'),L('vc5','Fam, you were so close.'),L('vc6','I can’t even roast that. Almost.'),L('vc7','Mate, that was nearly perfect.'),L('vc8','Okayyy! One more like that.'),L('vc9','Bro, you’re actually cooking.'),L('vc10','That was clean. Painfully close.'),L('vc11','Respect. That was close-close.'),L('vc12','Nah, that deserved better.')],
pb:[L('p1','Okayyy! I see you.'),L('p2','Wait... you got better?'),L('p3','Nah, who helped you?'),L('p4','Okay, that was kinda clean.'),L('p5','Bro actually locked in.'),L('p6','Look at you go!'),L('p7','Fine. That was good.'),L('p8','Who gave you skills?'),L('p9','Oh no. You’re learning.'),L('p10','Don’t get cocky now.'),L('p11','New best? Okay, respect.'),L('p12','My guy is improving!')],
streak:[L('st1','Aaaand you ruined it.'),L('st2','Bro sold the streak.'),L('st3','NOOO! You had it!'),L('st4','Fam. Why would you do that?'),L('st5','There goes the streak.'),L('st6','You fumbled so hard.'),L('st7','Bro choked.'),L('st8','I knew it wouldn’t last.'),L('st9','That streak deserved better.'),L('st10','Welp. Back to zero.'),L('st11','Bro had momentum too.'),L('st12','That one hurt me too.')],
perfect:[L('pf1','BRO?! Okay, calm down.'),L('pf2','Nah. Do that again.'),L('pf3','WAIT. You actually did it?!'),L('pf4','Okay, show-off.'),L('pf5','I hate that that was perfect.'),L('pf6','Who are you right now?'),L('pf7','Fine! You win this one.'),L('pf8','Bro turned into a robot.'),L('pf9','Nah, I need a replay.'),L('pf10','Okay. That was filthy.'),L('pf11','That was PERFECT perfect.'),L('pf12','Alright bro, you cooked me.')],
generic:[L('x1','Fam. Be serious.'),L('x2','Bro... no.'),L('x3','What was THAT?'),L('x4','Nah. Run it back.'),L('x5','My guy. Please.'),L('x6','You’re getting cooked.'),L('x7','That was rough.'),L('x8','Bro, lock in.'),L('x9','You can do better than THAT.'),L('x10','Mate. Come on.'),L('x11','Ain’t no way, bro.'),L('x12','Fam, I’m trying to help you.')],
interrupt:[L('i1','Oh. We’re just interrupting people now?'),L('i2','Fam, can I finish ONE sentence?'),L('i3','Bro keeps hitting retry like I’m not talking.'),L('i4','Nah. You definitely heard me talking.'),L('i5','DAMN. Can I finish?!'),L('i6','My guy, I have WORDS left.'),L('i7','You know what? Forget it. Go lose again.'),L('i8','Oh, don’t mind me. Clearly you’re busy.'),L('i9','I’m literally being bullied by a retry button.'),L('i10','Fine. Speedrun my disrespect too.'),L('i11','Nah nah, keep clicking. I wasn’t saying anything important.'),L('i12','This man has beef with complete sentences.'),L('i13','Bro, I was MID-SENTENCE.'),L('i14','Mate! Let me TALK.'),L('i15','Fam, you cut me off AGAIN.'),L('i16','You really said skip dialogue in real life.')],
respect:[L('rs1','Oh wow. You let me finish. Growth.'),L('rs2','Look at that. A full sentence. Beautiful.'),L('rs3','Thank you. I finally got to finish one.'),L('rs4','See? Listening wasn’t that painful.')],adBefore:[],adAfter:[]};
function addAside(text){const mr=q('#mr');if(!mr)return;mr.innerHTML='';const d=document.createElement('div');d.className='petty-aside';d.textContent=text;mr.appendChild(d)}
function pop(text){document.querySelector('.petty-pop')?.remove();const d=document.createElement('div');d.className='petty-pop';d.textContent='PETTY: '+text;document.body.appendChild(d);setTimeout(()=>d.remove(),2600)}
function complain(){if(window.__PETTY_AD_BANTER_LOCK)return false;const line=p(pools.interrupt);cutoffs=0;nextComplaintAt=5+Math.floor(Math.random()*2);pop(line.text);interruptAndSpeak(line.text,'interrupt');return true}
function noteCutoff(){if(window.__PETTY_AD_BANTER_LOCK||!voiceOn()||!speechActive)return;speechActive=false;cutoffs++;if(cutoffs>=nextComplaintAt)complain();else try{speechSynthesis.cancel()}catch{}}
document.addEventListener('pointerdown',e=>{if(e.target?.closest?.('#retry,#primary'))noteCutoff()},true);
function handleResult(){const modal=q('#modal');if(!modal||modal.classList.contains('hide'))return;const score=(q('#ms')?.textContent||'').trim(),game=(q('#mg')?.textContent||'').trim(),meta=(q('#mm')?.textContent||'').trim(),attempt=(q('#att')?.textContent||q('#tot')?.textContent||'').trim(),key=[game,score,meta,attempt].join('|');if(!score||key===lastResultKey)return;lastResultKey=key;const pb=/NEW PERSONAL BEST/i.test(meta);let pool=pools.generic,perfect=false,veryClose=false,good=false;if(game==='PERFECT TIMER'){const v=parseFloat(score);perfect=/^1\.000s$/.test(score);const diff=Math.abs(v-1);veryClose=!perfect&&diff<=.015;good=!perfect&&!veryClose&&diff<=.06;pool=perfect?pools.perfect:pb?pools.pb:veryClose?pools.veryClose:good?pools.good:pools.timer}else if(game==='PERFECT STOP'){const v=parseFloat(score);perfect=v>=99.95;veryClose=!perfect&&v>=97;good=!perfect&&!veryClose&&v>=90;pool=perfect?pools.perfect:pb?pools.pb:veryClose?pools.veryClose:good?pools.good:pools.stop}else if(game==='REACTION TEST'){if(score==='TOO EARLY')pool=pools.early;else{const v=parseFloat(score);perfect=v<=170;veryClose=!perfect&&v<=210;good=!perfect&&!veryClose&&v<=280;pool=perfect?pools.perfect:pb?pools.pb:veryClose?pools.veryClose:good?pools.good:v>=350?pools.slow:pools.reaction}}const line=p(pool);addAside(line.text);setTimeout(()=>{if(!window.__PETTY_AD_BANTER_LOCK&&!speechActive)interruptAndSpeak(line.text,'normal')},10)}
const modal=q('#modal');if(modal)new MutationObserver(handleResult).observe(modal,{attributes:true,attributeFilter:['class'],childList:true,characterData:true,subtree:true});window.PettyPersonality={version:'2.9',speak,interruptAndSpeak,choose:p,pools,showToast:pop,achievement:()=>false,emit:()=>{},getSpeechState:()=>({active:speechActive,kind:speechKind,cutoffs,nextComplaintAt})};
})();