/* 99% IMPOSSIBLE — Petty core v2.4: simple, savage, fast jokes */
(()=>{
const P=n=>'n99_petty_'+n,get=(n,d=null)=>{const v=localStorage.getItem(P(n));return v===null?d:v},set=(n,v)=>localStorage.setItem(P(n),String(v)),q=s=>document.querySelector(s);let speaking=false,lastResultKey='';
const style=document.createElement('style');style.textContent=`.petty-aside{margin:11px auto 2px;padding:8px 10px;max-width:340px;border:1px dashed rgba(255,255,255,.12);border-radius:8px;color:#b8b4c0;font-size:11px;font-weight:800;line-height:1.35}.petty-aside::before{content:'PETTY: ';color:var(--neon-pink,#FF2E95);letter-spacing:.7px}.petty-voice{position:fixed;z-index:40;width:46px;height:46px;border-radius:50%;border:2px solid rgba(255,255,255,.18);background:linear-gradient(180deg,#25202c,#121016);box-shadow:0 4px 14px rgba(0,0,0,.45);color:#fff;font-size:18px;touch-action:manipulation}.petty-voice.off{opacity:.55;filter:grayscale(.65)}body:has(#modal:not(.hide)) .petty-voice{opacity:.28;pointer-events:none}`;document.head.appendChild(style);
const voiceBtn=document.createElement('button');voiceBtn.className='petty-voice';voiceBtn.setAttribute('aria-label','Toggle Petty voice');document.body.appendChild(voiceBtn);
function voiceOn(){return get('voice','1')==='1'}function sync(){voiceBtn.textContent=voiceOn()?'🔊':'🔇';voiceBtn.classList.toggle('off',!voiceOn())}function chooseVoice(){const vs=speechSynthesis?.getVoices?.()||[];return vs.find(v=>/^en-GB/i.test(v.lang))||vs.find(v=>/^en-/i.test(v.lang))||null}function speak(text,force=false){if((!voiceOn()&&!force)||!text)return false;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),v=chooseVoice();if(v)u.voice=v;u.lang=v?.lang||'en-GB';u.rate=.98;u.pitch=.86;u.volume=1;speaking=true;u.onend=u.onerror=()=>speaking=false;speechSynthesis.speak(u);return true}catch{return false}}function interruptAndSpeak(t){try{speechSynthesis.cancel()}catch{}speaking=false;return speak(t)}
voiceBtn.onclick=()=>{set('voice',voiceOn()?'0':'1');if(!voiceOn())try{speechSynthesis.cancel()}catch{}sync()};sync();
const L=(id,text)=>({id,text,cooldown:1,repeat:true}),pick=a=>a[Math.floor(Math.random()*a.length)];
const pools={
timer:[L('t1','Bro. Can you count?'),L('t2','One second. ONE.'),L('t3','Fam, what was that?'),L('t4','Not even close, mate.'),L('t5','The timer just cooked you.'),L('t6','You guessed, didn’t you?'),L('t7','That was painful to watch.'),L('t8','My grandma counts faster.'),L('t9','Bro got beef with one second.'),L('t10','You had one job.'),L('t11','Mate. Count slower.'),L('t12','Mate. Count faster.'),L('t13','Was that your best guess?'),L('t14','The clock said absolutely not.'),L('t15','Yeah... try that again.')],
stop:[L('s1','Bro. The box was RIGHT there.'),L('s2','Did you close your eyes?'),L('s3','Fam, aim at the box.'),L('s4','You missed THAT?'),L('s5','The target is literally sitting still.'),L('s6','Mate. It does not move.'),L('s7','Where were you aiming?'),L('s8','Bro aimed at another game.'),L('s9','That was nasty. Not the good kind.'),L('s10','The box is laughing at you.'),L('s11','Almost! Just kidding.'),L('s12','Nah, you’re trolling me.'),L('s13','Your thumb said nope.'),L('s14','Fam. Open your eyes.'),L('s15','HOW did you miss that?')],
reaction:[L('r1','Bro fell asleep.'),L('r2','Hello? Anybody home?'),L('r3','Green means GO, mate.'),L('r4','Were you texting?'),L('r5','My grandma tapped first.'),L('r6','Bro needed a warm-up.'),L('r7','That thumb is on vacation.'),L('r8','Wake up, fam.'),L('r9','The green light got bored.'),L('r10','Mate, we are waiting.'),L('r11','You good over there?'),L('r12','Bro lagged in real life.'),L('r13','Your thumb said “five more minutes.”'),L('r14','That was SLOW slow.'),L('r15','I almost took a nap.')],
early:[L('e1','BRO. IT WASN’T GREEN.'),L('e2','What are you tapping?!'),L('e3','Fam, wait for green!'),L('e4','Bro fought an invisible light.'),L('e5','You panicked. I saw it.'),L('e6','Mate, calm DOWN.'),L('e7','You just tapped air.'),L('e8','Bro said “close enough.”'),L('e9','Green left the chat.'),L('e10','Too early, speedy.')],
slow:[L('sl1','Bro, wake UP.'),L('sl2','Were you making a sandwich?'),L('sl3','Fam, it’s been green.'),L('sl4','You can tap now, mate.'),L('sl5','That took forever.'),L('sl6','My guy went AFK.'),L('sl7','Bro needed directions.'),L('sl8','You missed the whole moment.'),L('sl9','Mate. Faster than THAT.'),L('sl10','The light gave up on you.')],
pb:[L('p1','Okayyy! I see you.'),L('p2','Wait... you got better?'),L('p3','Nah, who helped you?'),L('p4','Okay, that was kinda clean.'),L('p5','Bro actually locked in.'),L('p6','Look at you go!'),L('p7','Fine. That was good.'),L('p8','Who gave you skills?'),L('p9','Oh no. You’re learning.'),L('p10','Don’t get cocky now.')],
streak:[L('st1','Aaaand you ruined it.'),L('st2','Bro sold the streak.'),L('st3','NOOO! You had it!'),L('st4','Fam. Why would you do that?'),L('st5','There goes the streak.'),L('st6','You fumbled so hard.'),L('st7','Bro choked.'),L('st8','I knew it wouldn’t last.'),L('st9','That streak deserved better.'),L('st10','Welp. Back to zero.')],
perfect:[L('pf1','BRO?! Okay, calm down.'),L('pf2','Nah. Do that again.'),L('pf3','WAIT. You actually did it?!'),L('pf4','Okay, show-off.'),L('pf5','I hate that that was perfect.'),L('pf6','Who are you and what did you do with the bad player?'),L('pf7','Fine! You win this one.'),L('pf8','Bro turned into a robot.'),L('pf9','Nah, I need a replay.'),L('pf10','Okay. That was filthy.')],
generic:[L('g1','Fam. Be serious.'),L('g2','Bro... no.'),L('g3','What was THAT?'),L('g4','Nah. Run it back.'),L('g5','My guy. Please.'),L('g6','You’re getting cooked.'),L('g7','That was embarrassing.'),L('g8','Bro, lock in.'),L('g9','I know you can do better than THAT.'),L('g10','Mate. Come on.')],adBefore:[],adAfter:[]};
function choose(a){return pick(a)}function addAside(text){const mr=q('#mr');if(!mr)return;mr.querySelector('.petty-aside')?.remove();const d=document.createElement('div');d.className='petty-aside';d.textContent=text;mr.appendChild(d)}
function handleResult(){const modal=q('#modal');if(!modal||modal.classList.contains('hide'))return;const score=(q('#ms')?.textContent||'').trim(),game=(q('#mg')?.textContent||'').trim(),meta=(q('#mm')?.textContent||'').trim(),roast=(q('#mr')?.textContent||'').trim(),key=[game,score,meta].join('|');if(!score||key===lastResultKey)return;lastResultKey=key;const pb=/NEW PERSONAL BEST/i.test(meta),dead=/STREAK DEAD/i.test(roast),perfect=(game==='PERFECT TIMER'&&/^1\.000s$/.test(score))||(game==='PERFECT STOP'&&parseFloat(score)>=99.95)||(game==='REACTION TEST'&&parseFloat(score)<=170);let pool=perfect?pools.perfect:dead?pools.streak:pb?pools.pb:score==='TOO EARLY'?pools.early:(game==='REACTION TEST'&&parseFloat(score)>=350)?pools.slow:game==='PERFECT TIMER'?pools.timer:game==='PERFECT STOP'?pools.stop:game==='REACTION TEST'?pools.reaction:pools.generic;const line=choose(pool);addAside(line.text);setTimeout(()=>interruptAndSpeak(line.text),10)}
const modal=q('#modal');if(modal)new MutationObserver(handleResult).observe(modal,{attributes:true,attributeFilter:['class'],childList:true,characterData:true,subtree:true});window.PettyPersonality={version:'2.4',speak,interruptAndSpeak,choose,pools,showToast:()=>{},achievement:()=>false,emit:()=>{}};
})();