/* 99% IMPOSSIBLE — integrated Reaction Test v1.2
   - Silent unpredictable 1–5s wait (no learnable rhythm)
   - Reliable START/GO/tap sound cues on mobile Safari
   - Physical-press timestamp is authoritative when supplied
   - GO and press timestamps are normalized to performance.now() origin
   - One result object drives percentage, PB, tier, near-miss, Petty and share copy
*/
(()=>{
'use strict';
const POINTS=[[150,100],[180,99.5],[200,99],[230,97.5],[250,95.5],[300,90],[350,80],[500,50],[700,0]];
function reactionPercent(ms){if(ms<=150)return 100;for(let i=1;i<POINTS.length;i++){const [b,pb]=POINTS[i],[a,pa]=POINTS[i-1];if(ms<=b)return Math.max(0,Math.min(100,pa+(pb-pa)*((ms-a)/(b-a))))}return 0}
function reactionTier(ms){if(ms<100)return'suspicious';if(ms<120)return'extreme';if(ms<150)return'elite';if(ms<=180)return'perfect';if(ms<=210)return'epic';if(ms<=250)return'strong';if(ms<=300)return'subtle';return'fail'}
const style=document.createElement('style');style.textContent=`
.g-reaction #play,.g-reaction .rx{touch-action:none;-webkit-user-select:none;user-select:none}
.g-reaction #primary{touch-action:manipulation;-webkit-user-select:none;user-select:none}
body.reaction-suspicious .modalbox{border-color:#8B5CF6!important;box-shadow:0 0 48px rgba(139,92,246,.55),0 14px 45px rgba(0,0,0,.78)!important}
body.reaction-suspicious .modalbox .score{color:#C4B5FD!important;text-shadow:0 0 26px rgba(139,92,246,.75)!important}
body.reaction-elite .modalbox{border-color:#00D8F6!important;box-shadow:0 0 55px rgba(0,216,246,.5),0 14px 45px rgba(0,0,0,.78)!important}`;document.head.appendChild(style);
const suspiciousPetty=[{id:'rxbot01',text:'Are you a robot?'},{id:'rxbot02',text:'That was not supposed to happen.'},{id:'rxbot03',text:'One hundred percent a glitch.'},{id:'rxbot04',text:'Who are you paying to tap for you?'},{id:'rxbot05',text:'Nah. Run that back.'},{id:'rxbot06',text:'I said react. Not predict the future.'},{id:'rxbot07',text:'Bro tapped before his brain got the notification.'},{id:'rxbot08',text:'Absolutely not. Do it again.'}];
const elitePetty=[{id:'rxelite01',text:'That percentage is disgusting. Do it again.'},{id:'rxelite02',text:'Okay, those reflexes are actually suspicious.'},{id:'rxelite03',text:'One hundred percent? Calm down, robot.'},{id:'rxelite04',text:'Nah. That was elite elite.'}];
const fastPetty=[{id:'rxpct01',text:'Look at that percentage. Your thumb finally woke up.'},{id:'rxpct02',text:'That percentage is getting dangerous.'},{id:'rxpct03',text:'Okay. The milliseconds and the percentage both say you cooked.'},{id:'rxpct04',text:'Now THAT percentage actually looks respectable.'}];
function publish(result){window.N99ReactionResult=result;try{window.dispatchEvent(new CustomEvent('n99:reaction-result',{detail:result}))}catch{}return result}
function armReactionPetty(result){const pp=window.PettyPersonality;if(!pp?.pools||!result||!Number.isFinite(result.reactionMs))return()=>{};let pool=null;if(result.tier==='suspicious'){pool=suspiciousPetty;pp.pools.suspicious=suspiciousPetty}else if(['extreme','elite','perfect'].includes(result.tier))pool=elitePetty;else if(['epic','strong'].includes(result.tier))pool=fastPetty;if(!pool)return()=>{};const m=result.reactionMs,key=m<=170?'perfect':m<=210?'veryClose':m<=280?'good':m>=350?'slow':'reaction';if(!Array.isArray(pp.pools[key]))return()=>{};const old=pp.pools[key];pp.pools[key]=pool;return()=>setTimeout(()=>{if(pp.pools[key]===pool)pp.pools[key]=old},0)}
function safeResumeAudio(){try{const c=typeof audio==='function'?audio():null;if(c?.state==='suspended'&&c.resume)c.resume().catch?.(()=>{});return c}catch{return null}}
function cue(notes){try{const c=safeResumeAudio();if(!c)return;const playNotes=()=>notes.forEach((n,i)=>tone(n[0],n[1]||.05,n[2]||'sine',n[3]||.035,n[4]??i*.045));if(c.state==='running')playNotes();else c.resume?.().then(()=>{if(c.state==='running')playNotes()}).catch(()=>{})}catch{}}
function normalizePressTime(value){const now=performance.now(),raw=Number(value);if(!Number.isFinite(raw)||raw>1e12||Math.abs(raw-now)>60000)return now;return raw}
window.N99ReactionScoring={reactionPercent,reactionTier,normalizePressTime};
rxStart=function(){safeResumeAudio();cue([[330,.045,'sine',.03],[440,.045,'sine',.025,.055]]);st.run=1;st.ready=0;st.start=0;primary.textContent='WAIT FOR GREEN…';untick();const r=play.querySelector('.rx');r.className='rx wait';r.innerHTML='<b>WAIT…</b><div>Do not tap yet. The whole box will turn GREEN.</div>';const delay=1000+Math.random()*4000;st.to=setTimeout(()=>{if(!st.run)return;st.ready=1;st.start=performance.now();r.className='rx go';r.innerHTML='<b>GO!</b><div>TAP THIS GREEN BOX NOW</div>';primary.textContent='TAP GREEN BOX!';cue([[920,.07,'square',.06],[1240,.05,'sine',.035,.045]]);navigator.vibrate?.(30)},delay)};
rxHit=function(pressTime){if(!st.run)return;safeResumeAudio();if(!st.ready){clearTimeout(st.to);untick();st.run=0;bump();streak(false);publish({reactionMs:null,reactionPercent:null,isPB:false,pbGap:null,tier:'too-early'});const r=play.querySelector('.rx');r.className='rx early';r.innerHTML='<b>TOO EARLY</b><div>Wait for BRIGHT GREEN.</div>';show('TOO EARLY',pick(ROAST.reaction.early),'NO TIME RECORDED','I got baited by Reaction Test in 99% IMPOSSIBLE and tapped TOO EARLY 💀 bet you do the same.','fail',false,true,'');primary.textContent='TRY AGAIN';return window.N99ReactionResult}
const at=normalizePressTime(pressTime),go=Number.isFinite(st.start)?st.start:performance.now(),reactionMs=Math.max(0,at-go);cue([[1080,.028,'square',.026]]);st.run=st.ready=0;bump();const raw=localStorage.getItem(K('reaction_best')),old=raw===null?null:+raw,isPB=old===null||reactionMs<old;if(isPB)S('reaction_best',reactionMs);const pct=Math.round((reactionPercent(reactionMs)+Number.EPSILON)*10)/10,pbGap=old===null?null:reactionMs-old,result=publish({reactionMs,reactionPercent:pct,isPB,pbGap,tier:reactionTier(reactionMs)});streak(reactionMs<=230);const ro=reactionMs<180?pick(ROAST.reaction.elite):reactionMs<=250?pick(ROAST.reaction.good):pick(ROAST.reaction.slow),delta=deltaMark('reaction_lastMs',reactionMs,'ms',0),suspicious=result.tier==='suspicious',restorePetty=armReactionPetty(result),visualTier=suspicious?'subtle':result.tier==='extreme'||result.tier==='elite'?'epic':rtier(reactionMs),label=suspicious?'🤖 SUSPICIOUSLY FAST':result.tier==='extreme'?'EXTREMELY FAST':result.tier==='elite'?'ELITE REACTION':'REACTION TIME';const done=()=>{show(Math.round(reactionMs)+'ms',ro,pct.toFixed(1)+'% · '+label,`I hit ${Math.round(reactionMs)}ms (${pct.toFixed(1)}%) on Reaction Test in 99% IMPOSSIBLE ⚡ bet your reflexes are slower.`,visualTier,isPB,visualTier==='fail',delta);restorePetty();document.body.classList.toggle('reaction-suspicious',suspicious);document.body.classList.toggle('reaction-elite',result.tier==='extreme'||result.tier==='elite');primary.textContent='TRY AGAIN'};if(reactionMs>=231&&reactionMs<=250&&old!==null&&!isPB&&pbGap>0&&pbGap<=6)nearReveal('reaction',Math.round(pbGap)+'ms FROM YOUR BEST','SO CLOSE',done);else done();return result};
})();
